- name: Create filesystem
  file:
    path: {{ item }}
    state: directory
    owner: {{nfs_user}}
    group: {{nfs_group}}
    mode: 0700
  with_items:
    - {{ exportfs.*.dir }}

- name: Mount filesystem
  mount:
    src: {{ item }}
    path: "/nfs/{{ item }}"
    state: mounted
  with_items:
    - {{ exportfs.*.dir }}

- name: Configure general settings
  template:
    src: "{{module_path}}/exports.j2"
    dest: "{{ nfs_exportfs_path }}/exports"
    owner: root
    group: root
    mode: 0600