BASE_IMAGE = "fewpixels/Ubuntu20base"
PROVIDER = "virtualbox"
VERSION = "0.2"

BASH_PATH = "../../provisioning/scripts/"
ANSIBLE_PATH = "provisioning/"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.box_check_update = true
  #config.ssh.insert_key = false
  #config.ssh.private_key_path ="./authorized_keys"

config.vm.define "nameserver" do |server|
  server.vm.box = BASE_IMAGE
  server.vm.box_version = VERSION
  server.vm.hostname = "nameserver"
  server.vm.network "private_network", ip: "10.0.1.2"
  server.vm.provider PROVIDER do |vb|
    vb.name = "nameserver"
    vb.cpus = 1
    vb.memory = 512
    vb.linked_clone = true
  end
  #server.vm.provision "shell", path: "#{BASH_PATH}bootstrap.sh"
end

config.vm.define "nfs" do |server|
  server.vm.box = BASE_IMAGE
  server.vm.box_version = VERSION
  server.vm.hostname = "nfs-1"
  server.vm.network "private_network", ip: "10.0.1.3"
  server.vm.network "private_network", ip: "10.1.1.2"
  server.vm.provider PROVIDER do |vb|
    vb.name = "nfs"
    vb.cpus = 1
    vb.memory = 512
  end
  #server.vm.provision "shell", path: "#{BASH_PATH}/bootstrap.sh"
  #server.vm.provision "ansible_local" do |ansible|
  #end
end

#  config.vm.define "" do |server|
#    server.vm.box = BASE_IMAGE
#    server.vm.box_version = VERSION
#    server.vm.hostname = ""
#    server.vm.network "private_network", ip: "10.1.1.4"
#    server.vm.provider PROVIDER do |vb|
#      vb.name = ""
#      vb.cpus = 1
#      vb.memory = 512
#    end
#    server.vm.provision "shell", path: "#{BASH_PATH}bootstrap.sh"
#    server.vm.provision "ansible_local" do |ansible|
#      puppet.playbook = ""
#      end
#  end

end