USE bank IF bank NOT IN (SHOW FULL PROCESSLIST);
DROP TABLE IF EXISTS owner;
CREATE TABLE IF NOT EXISTS owner(
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(25) NOT NULL,
	family VARCHAR(50) NOT NULL,
	registration_date DATE NOT NULL
);
LOAD DATA LOCAL INFILE 'csv/owner.csv' 
INTO TABLE owner
FIELDS TERMINATED BY ';' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

