USE bank IF bank NOT IN SHOW FULL PROCESSLIST;

SET @res := (SELECT EXISTS (
	SELECT `COLUMN_NAME`  FROM `INFORMATION_SCHEMA`.`COLUMNS`
       	WHERE `TABLE_SCHEMA`='bank'
	AND `TABLE_NAME`='card'
	AND COLUMN_NAME='balance'
))

--IF NULL IN SELECT @res THEN
--ALTER TABLE card
--ADD COLUMN balance;
--END IF;

START TRANSACTION;
UPDATE card SET balance = CAST( FLOOR( ( RAND() + 1 ) ) AS UNSIGNED );
SELECT EXISTS (
	SELECT balance FROM card WHERE balance IS NOT NULL
) THEN ROLLBACK ELSE COMMIT;

