- name: Configure general settings
  template:
    src: "{{item}}.j2"
    dest: "{{ postgresql_config_path }}/{{item}}.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  with_items:
    - postgresql
    - pg_hba