- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Install PostgreSQL packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev

- name: Ensure PostgreSQL unix socket dirs exist.
  file:
    path: "{{ postgresql_socket_directories }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 600
