- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Install nfs components
  package:
    state: present
    name: nfs-kernel-server
