- name: Install nfs server
import_tasks: "{{ module_path }}/install.yaml"

- name: Firewall for nfs
import_tasks: "{{ module_path }}/firewall.yaml"
  
- name: Create and export directories 
import_tasks: "{{ module_path }}/filesystem.yaml"