VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/bionic64"
#   libvirt.connect_via_ssh = false
#   libvirt.username = "root"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
#     libvirt.name = "server"
#     libvirt.host = "server.com"
     v.memory = 512
     v.cpus = 1
  end

  config.vm.hostname = "server"
  config.vm.network :private_network, ip: "192.168.33.33"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
#   config.vm.define :server do |server|
#   end

  # Ansible provisioner.
    config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "vagrant.yml"
    ansible.inventory_path = "hosts.yml"
    ansible.become = true
  end

end