SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

UPDATE card
SET expiration_date = CURDATE()
WHERE expiration_date = NULL OR expiration_date = DATE('0000-00-00');

UPDATE owner
SET registration_date = CURDATE()
WHERE registration_date = NULL OR registration_date = DATE('0000-00-00');

SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

