DELIMITER //

CREATE PROCEDURE GEN_RANDOM_CARD() RETURNS CARD_TYPE
BEGIN	
	CREATE TEMPORARY TABLE temp_struct(symbol VARCHAR(1) NOT NULL)
	INSERT INTO temp_struct(symbol) VALUES (CAST(ROUND(RAND() * 9) % 10) AS  VARCHAR(1)) LIMIT 1,12;
	SET @str = CONCAT(SELECT symbol FROM temp_struct);
	DROP temp_struct;
	RETURN @str;
END //

DELIMITER ;

ALTER TABLE card
ADD card_num VARCHAR(12);

UPDATE card
SET card_num = CALL GEN_RANDOM_CARD();

DROP PROCEDURE IF EXISTS GEN_RANDOM_CARD //

ALTER TABLE card
ADD CONSTRAINT card_num NOT NULL;

ALTER TABLE card
ADD CONSTRAINT pattern_check CHECK (LENGTH(card_num) = 12);
